package Vista;

import Controlador.Controlador;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author pri23
 */
public class Principal extends javax.swing.JFrame {
    Controlador contrl = new Controlador();
               
    /**
     * Creates new form Principal
     */
    public Principal(){
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rQRegCursos = new javax.swing.JFrame();
        labelRegistroCursos = new javax.swing.JLabel();
        labelEscuela = new javax.swing.JLabel();
        labelNombreCurso = new javax.swing.JLabel();
        labelCodCurso = new javax.swing.JLabel();
        labelCreditosCurso = new javax.swing.JLabel();
        labelHorasLectivas = new javax.swing.JLabel();
        tNombreCurso = new javax.swing.JTextField();
        cbNombresEscuelas = new javax.swing.JComboBox<>();
        tNumCodCurso = new javax.swing.JTextField();
        cbNumCreditos = new javax.swing.JComboBox<>();
        cbCantHorasLectivas = new javax.swing.JComboBox<>();
        bRegistrarCurso = new javax.swing.JButton();
        bLimpiarCamposRegCurso = new javax.swing.JButton();
        lbCodEscuelaCodCurso = new javax.swing.JLabel();
        rQRegistrarEsqArea = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tNombreEA = new javax.swing.JTextField();
        tCodigoEscuela = new javax.swing.JTextField();
        bRegEsqArea = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        rqRegistrarRequeCorreque = new javax.swing.JFrame();
        rqAsignarPlanDeEstudio = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboxPlanesEst = new javax.swing.JComboBox<>();
        txtCodigoPlan = new javax.swing.JTextField();
        txtVigenciaPlan = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoCurso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cboxBloqueActivo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        bPropioRegistroVentana = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBInterfRegPlanesEstudio = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        labelRegistroCursos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRegistroCursos.setText("Registro de Cursos");

        labelEscuela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelEscuela.setText("Escuela propietaria del curso: ");

        labelNombreCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombreCurso.setText("Nombre del curso:");

        labelCodCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCodCurso.setText("Código del curso:");

        labelCreditosCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCreditosCurso.setText("Créditos:");

        labelHorasLectivas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelHorasLectivas.setText("Horas lectivas: ");

        tNombreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreCursoActionPerformed(evt);
            }
        });

        cbNombresEscuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNombresEscuelasActionPerformed(evt);
            }
        });

        tNumCodCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNumCodCursoActionPerformed(evt);
            }
        });

        bRegistrarCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bRegistrarCurso.setText("Registrar");
        bRegistrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarCursoActionPerformed(evt);
            }
        });

        bLimpiarCamposRegCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bLimpiarCamposRegCurso.setText("Limpiar Campos");
        bLimpiarCamposRegCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarCamposRegCursoActionPerformed(evt);
            }
        });

        lbCodEscuelaCodCurso.setText("COD");

        javax.swing.GroupLayout rQRegCursosLayout = new javax.swing.GroupLayout(rQRegCursos.getContentPane());
        rQRegCursos.getContentPane().setLayout(rQRegCursosLayout);
        rQRegCursosLayout.setHorizontalGroup(
            rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rQRegCursosLayout.createSequentialGroup()
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rQRegCursosLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(bRegistrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(bLimpiarCamposRegCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rQRegCursosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombreCurso)
                            .addComponent(labelEscuela)
                            .addComponent(labelCodCurso)
                            .addComponent(labelCreditosCurso)
                            .addComponent(labelHorasLectivas))
                        .addGap(34, 34, 34)
                        .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rQRegCursosLayout.createSequentialGroup()
                                .addComponent(lbCodEscuelaCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tNumCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbNombresEscuelas, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRegistroCursos)
                            .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbCantHorasLectivas, javax.swing.GroupLayout.Alignment.LEADING, 0, 54, Short.MAX_VALUE)
                                .addComponent(cbNumCreditos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        rQRegCursosLayout.setVerticalGroup(
            rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rQRegCursosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelRegistroCursos)
                .addGap(31, 31, 31)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEscuela)
                    .addComponent(cbNombresEscuelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreCurso)
                    .addComponent(tNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodCurso)
                    .addComponent(tNumCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodEscuelaCodCurso))
                .addGap(18, 18, 18)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCreditosCurso)
                    .addComponent(cbNumCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHorasLectivas)
                    .addComponent(cbCantHorasLectivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegistrarCurso)
                    .addComponent(bLimpiarCamposRegCurso))
                .addGap(36, 36, 36))
        );

        rQRegistrarEsqArea.setMinimumSize(new java.awt.Dimension(1000, 1000));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Registrar Escuela o Área Académica");

        jLabel4.setText("Nombre: ");

        jLabel5.setText("Código");

        tCodigoEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCodigoEscuelaActionPerformed(evt);
            }
        });

        bRegEsqArea.setText("Registrar");
        bRegEsqArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegEsqAreaActionPerformed(evt);
            }
        });

        jButton6.setText("Limpiar Casillas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tNombreEA, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(tCodigoEscuela)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(bRegEsqArea)
                        .addGap(63, 63, 63)
                        .addComponent(jButton6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tNombreEA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tCodigoEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegEsqArea)
                    .addComponent(jButton6))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout rQRegistrarEsqAreaLayout = new javax.swing.GroupLayout(rQRegistrarEsqArea.getContentPane());
        rQRegistrarEsqArea.getContentPane().setLayout(rQRegistrarEsqAreaLayout);
        rQRegistrarEsqAreaLayout.setHorizontalGroup(
            rQRegistrarEsqAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rQRegistrarEsqAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rQRegistrarEsqAreaLayout.setVerticalGroup(
            rQRegistrarEsqAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rQRegistrarEsqAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout rqRegistrarRequeCorrequeLayout = new javax.swing.GroupLayout(rqRegistrarRequeCorreque.getContentPane());
        rqRegistrarRequeCorreque.getContentPane().setLayout(rqRegistrarRequeCorrequeLayout);
        rqRegistrarRequeCorrequeLayout.setHorizontalGroup(
            rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        rqRegistrarRequeCorrequeLayout.setVerticalGroup(
            rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Registro de Planes de Estudio ");

        jLabel6.setText("Escuela asociada del plan:");

        jLabel8.setText("Código del plan de estudios:");

        jLabel9.setText("Vigencia del plan de estudios:");

        cboxPlanesEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPlanesEstActionPerformed(evt);
            }
        });

        txtVigenciaPlan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtVigenciaPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVigenciaPlanActionPerformed(evt);
            }
        });

        jLabel11.setText("Código del curso que forma parte del plan: ");

        jLabel12.setText("Bloque");

        bPropioRegistroVentana.setText("Registrar cursos en el plan de estudios");
        bPropioRegistroVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPropioRegistroVentanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bPropioRegistroVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(bPropioRegistroVentana)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rqAsignarPlanDeEstudioLayout = new javax.swing.GroupLayout(rqAsignarPlanDeEstudio.getContentPane());
        rqAsignarPlanDeEstudio.getContentPane().setLayout(rqAsignarPlanDeEstudioLayout);
        rqAsignarPlanDeEstudioLayout.setHorizontalGroup(
            rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(32, 32, 32)
                        .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxPlanesEst, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboxBloqueActivo, javax.swing.GroupLayout.Alignment.LEADING, 0, 177, Short.MAX_VALUE)
                                .addComponent(txtCodigoCurso, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtVigenciaPlan, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rqAsignarPlanDeEstudioLayout.setVerticalGroup(
            rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addGap(47, 47, 47)
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboxPlanesEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtVigenciaPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cboxBloqueActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Registrar escuela o Área Académica");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Registrar Cursos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBInterfRegPlanesEstudio.setText("Registro de Planes de Estudio");
        jBInterfRegPlanesEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInterfRegPlanesEstudioActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");

        jLabel1.setText("PD: So, sorry por la falta de colores y diseño ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("PD: Ya los botones estan funcionales de esos dos, por si quieres correr la vara desde interfaz, pero no le pongas que recuerde siempre que ese es el main");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBInterfRegPlanesEstudio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBInterfRegPlanesEstudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCodigoEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCodigoEscuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCodigoEscuelaActionPerformed

    private void bRegEsqAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegEsqAreaActionPerformed
        Controlador entradaCon = new Controlador();
        if(this.tNombreEA.getText().equals("")){
            JOptionPane.showMessageDialog(null,"¡Espacio en blanco! Por favor, ingrese un nombre de escuela válido");
        }
        
            
        if(this.tCodigoEscuela.getText().equals("")){
            JOptionPane.showMessageDialog(null,"¡Espacio en blanco! Por favor, ingrese un codigo de escuela válido");
        }
        try {
            entradaCon.crearEscuela(tNombreEA.getText(), tCodigoEscuela.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bRegEsqAreaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    this.tCodigoEscuela.setText(null);
    this.tNombreEA.setText(null);
    }//GEN-LAST:event_jButton6ActionPerformed


    private void nombresEscuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresEscuelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresEscuelasActionPerformed

    private void nombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCursoActionPerformed

    private void numCodCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCodCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCodCursoActionPerformed

    private void numCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCreditosActionPerformed

    private void cantHorasLectivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantHorasLectivasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantHorasLectivasActionPerformed

    private void bRegistrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarCursoActionPerformed
        Controlador entradaCon = new Controlador();
        //String nombreEscuela = cbNombresEscuelas.getSelectedItem().toString();
        if(this.tNombreCurso.getText().equals("")){
            JOptionPane.showMessageDialog(null,"¡Espacio en blanco! Por favor, ingrese un nombre de curso válido");
        }
        //validar que no repita el nombre
        
        String numCodCurso = this.tNumCodCurso.getText();
        if(this.tNumCodCurso.getText().equals("")){
            JOptionPane.showMessageDialog(null,"¡Espacio en blanco! Por favor, ingrese un número de curso válido");
        }
        
        try{
            int intCodCurso = Integer.parseInt(numCodCurso);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"¡Entrada inválida! Por favor, ingrese un número entero para el curso");
        }
        
        int cantCreditos = Integer.valueOf(cbNumCreditos.getSelectedItem().toString());        
        int cantHorasLectivas = Integer.valueOf(cbCantHorasLectivas.getSelectedItem().toString());
        
        String codCurso = seleccionarCodigoEscuela() + this.tNumCodCurso.getText();

        //validar num de 4 dig
        //validar que no repita el num 
        
        entradaCon.crearCurso(seleccionarCodigoEscuela(), this.tNombreCurso.getText(), codCurso, cantCreditos, cantHorasLectivas);
         
        
    }//GEN-LAST:event_bRegistrarCursoActionPerformed

    private void bLimpiarCamposRegCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarCamposRegCursoActionPerformed
        this.tNombreCurso.setText(null);
        this.tNumCodCurso.setText(null);
        this.lbCodEscuelaCodCurso.setText(null);
    }//GEN-LAST:event_bLimpiarCamposRegCursoActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    private void botonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cbNombresEscuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNombresEscuelasActionPerformed
        String nombreEscuela = cbNombresEscuelas.getSelectedItem().toString();
        String codEscuela = contrl.obtenerCodEscuela(nombreEscuela); 
        System.out.println(codEscuela);
        this.lbCodEscuelaCodCurso.setText(codEscuela);
    }//GEN-LAST:event_cbNombresEscuelasActionPerformed

    private void tNumCodCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNumCodCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNumCodCursoActionPerformed

    private void tNombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreCursoActionPerformed

    private void txtVigenciaPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVigenciaPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVigenciaPlanActionPerformed

    private void jBInterfRegPlanesEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInterfRegPlanesEstudioActionPerformed
        contrl.poblarCboxEscuelas2(cboxPlanesEst);
        poblarCboxBloqueActivo(cboxBloqueActivo);
        this.rqAsignarPlanDeEstudio.setVisible(true);
    }//GEN-LAST:event_jBInterfRegPlanesEstudioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        contrl.poblarCboxEscuelas(cbNombresEscuelas);
        poblarCboxCreditos(cbNumCreditos);
        poblarCboxHorasLectivas(cbCantHorasLectivas);
        this.rQRegCursos.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.rQRegistrarEsqArea.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboxPlanesEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPlanesEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxPlanesEstActionPerformed

    private void bPropioRegistroVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPropioRegistroVentanaActionPerformed
        contr1.crearPlanEstudios
    }//GEN-LAST:event_bPropioRegistroVentanaActionPerformed

    private String seleccionarCodigoEscuela(){
        String nombreEscuela = cbNombresEscuelas.getSelectedItem().toString();
        String codEscuela = contrl.obtenerCodEscuela(nombreEscuela); 
        return codEscuela;
    }
    
    private void poblarCboxCreditos(JComboBox cbox_Creditos){
        int contador = 0;
        while (10 > contador){
            cbox_Creditos.addItem(contador);
            contador++;
        }   
    } 
    
    private void poblarCboxHorasLectivas(JComboBox cbox_horasLectivas){
        int contador = 0;
        while (24 > contador){
            cbox_horasLectivas.addItem(contador);
            contador++;
        }  
    }
    
    private void poblarCboxBloqueActivo(JComboBox cboxBloqueActivo){
        int contador = 0;
        String[] listaBloques = {"I Semestre","II Semestre", "Verano"};
        for(int i=0; i<listaBloques.length ;++i){
            cboxBloqueActivo.addItem(listaBloques[i]);
            contador++;
        }  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLimpiarCamposRegCurso;
    private javax.swing.JButton bPropioRegistroVentana;
    private javax.swing.JButton bRegEsqArea;
    private javax.swing.JButton bRegistrarCurso;
    private javax.swing.JComboBox<String> cbCantHorasLectivas;
    private javax.swing.JComboBox<String> cbNombresEscuelas;
    private javax.swing.JComboBox<String> cbNumCreditos;
    private javax.swing.JComboBox<String> cboxBloqueActivo;
    private javax.swing.JComboBox<String> cboxPlanesEst;
    private javax.swing.JButton jBInterfRegPlanesEstudio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelCodCurso;
    private javax.swing.JLabel labelCreditosCurso;
    private javax.swing.JLabel labelEscuela;
    private javax.swing.JLabel labelHorasLectivas;
    private javax.swing.JLabel labelNombreCurso;
    private javax.swing.JLabel labelRegistroCursos;
    private javax.swing.JLabel lbCodEscuelaCodCurso;
    private javax.swing.JFrame rQRegCursos;
    private javax.swing.JFrame rQRegistrarEsqArea;
    private javax.swing.JFrame rqAsignarPlanDeEstudio;
    private javax.swing.JFrame rqRegistrarRequeCorreque;
    private javax.swing.JTextField tCodigoEscuela;
    private javax.swing.JTextField tNombreCurso;
    private javax.swing.JTextField tNombreEA;
    private javax.swing.JTextField tNumCodCurso;
    private javax.swing.JTextField txtCodigoCurso;
    private javax.swing.JTextField txtCodigoPlan;
    private javax.swing.JFormattedTextField txtVigenciaPlan;
    // End of variables declaration//GEN-END:variables
}
