package Vista;

import Controlador.Controlador;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author pri23
 */
public class Principal extends javax.swing.JFrame {
    Controlador contrl = new Controlador();
    
               
    /**
     * Creates new form Principal
     */
    public Principal(){
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rQRegCursos = new javax.swing.JFrame();
        labelRegistroCursos = new javax.swing.JLabel();
        labelEscuela = new javax.swing.JLabel();
        labelNombreCurso = new javax.swing.JLabel();
        labelCodCurso = new javax.swing.JLabel();
        labelCreditosCurso = new javax.swing.JLabel();
        labelHorasLectivas = new javax.swing.JLabel();
        tNombreCurso = new javax.swing.JTextField();
        cbNombresEscuelas = new javax.swing.JComboBox<>();
        tNumCodCurso = new javax.swing.JTextField();
        cbNumCreditos = new javax.swing.JComboBox<>();
        cbCantHorasLectivas = new javax.swing.JComboBox<>();
        bRegistrarCurso = new javax.swing.JButton();
        bLimpiarCamposRegCurso = new javax.swing.JButton();
        lbCodEscuelaCodCurso = new javax.swing.JLabel();
        rQRegistrarEsqArea = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tNombreEA = new javax.swing.JTextField();
        tCodigoEscuela = new javax.swing.JTextField();
        bRegEsqArea = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        rqRegistrarRequeCorreque = new javax.swing.JFrame();
        lbAsignarReqCorreq = new javax.swing.JLabel();
        lbEscuelaPropietariaCurso = new javax.swing.JLabel();
        cbEscuelasPropietariasCurso = new javax.swing.JComboBox<>();
        lbCodCurso = new javax.swing.JLabel();
        cbCodigosCursosDeEscuela = new javax.swing.JComboBox<>();
        lbReqs = new javax.swing.JLabel();
        lbCorreqs = new javax.swing.JLabel();
        lbCodCursoReq = new javax.swing.JLabel();
        lbCodCursoCorreq = new javax.swing.JLabel();
        cbCodigoCursoReq = new javax.swing.JComboBox<>();
        cbCodigoCursoCorreq = new javax.swing.JComboBox<>();
        bRegistrarRequisito = new javax.swing.JButton();
        bRegistrarCorrequisito = new javax.swing.JButton();
        bCerrarRegReqCorreq = new javax.swing.JButton();
        rqAsignarPlanDeEstudio = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboxPlanesEst = new javax.swing.JComboBox<>();
        txtCodigoPlan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoCurso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cboxBloqueActivo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        bPropioRegistroVentana = new javax.swing.JButton();
        CalendVigencia = new com.toedter.calendar.JCalendar();
        rqConsultaPlanEstudio = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jEscuelaprop = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jMostrarCodPlan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bPDFCorreo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPlanEstudio = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jMostrarVigencia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        bVentanaRegistrarEscuela = new javax.swing.JButton();
        bVentanaRegistrarCursos = new javax.swing.JButton();
        jBInterfRegPlanesEstudio = new javax.swing.JButton();
        jBVisualizarPlanes = new javax.swing.JButton();
        bVentanaRegistrarReqCorreq = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bVentanaConsultarPlanesConCiertoCurso = new javax.swing.JButton();
        bVentanaConsultarRequisitos = new javax.swing.JButton();
        bVentanaConsultarCorrequisitos = new javax.swing.JButton();
        bVentanaEliminarReqCurso = new javax.swing.JButton();
        bVentanaEliminarCursoPlanDeEstudio = new javax.swing.JButton();
        bVentanaEliminarCurso = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        labelRegistroCursos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRegistroCursos.setText("Registro de Cursos");

        labelEscuela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelEscuela.setText("Escuela propietaria del curso: ");

        labelNombreCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNombreCurso.setText("Nombre del curso:");

        labelCodCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCodCurso.setText("Código del curso:");

        labelCreditosCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCreditosCurso.setText("Créditos:");

        labelHorasLectivas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelHorasLectivas.setText("Horas lectivas: ");

        tNombreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreCursoActionPerformed(evt);
            }
        });

        cbNombresEscuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNombresEscuelasActionPerformed(evt);
            }
        });

        tNumCodCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNumCodCursoActionPerformed(evt);
            }
        });

        bRegistrarCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bRegistrarCurso.setText("Registrar");
        bRegistrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarCursoActionPerformed(evt);
            }
        });

        bLimpiarCamposRegCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bLimpiarCamposRegCurso.setText("Limpiar Campos");
        bLimpiarCamposRegCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarCamposRegCursoActionPerformed(evt);
            }
        });

        lbCodEscuelaCodCurso.setText("COD");

        javax.swing.GroupLayout rQRegCursosLayout = new javax.swing.GroupLayout(rQRegCursos.getContentPane());
        rQRegCursos.getContentPane().setLayout(rQRegCursosLayout);
        rQRegCursosLayout.setHorizontalGroup(
            rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rQRegCursosLayout.createSequentialGroup()
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rQRegCursosLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(bRegistrarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(bLimpiarCamposRegCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rQRegCursosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombreCurso)
                            .addComponent(labelEscuela)
                            .addComponent(labelCodCurso)
                            .addComponent(labelCreditosCurso)
                            .addComponent(labelHorasLectivas))
                        .addGap(34, 34, 34)
                        .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rQRegCursosLayout.createSequentialGroup()
                                .addComponent(lbCodEscuelaCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tNumCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbNombresEscuelas, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRegistroCursos)
                            .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbCantHorasLectivas, javax.swing.GroupLayout.Alignment.LEADING, 0, 54, Short.MAX_VALUE)
                                .addComponent(cbNumCreditos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        rQRegCursosLayout.setVerticalGroup(
            rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rQRegCursosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelRegistroCursos)
                .addGap(31, 31, 31)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEscuela)
                    .addComponent(cbNombresEscuelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreCurso)
                    .addComponent(tNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodCurso)
                    .addComponent(tNumCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCodEscuelaCodCurso))
                .addGap(18, 18, 18)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCreditosCurso)
                    .addComponent(cbNumCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHorasLectivas)
                    .addComponent(cbCantHorasLectivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(rQRegCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegistrarCurso)
                    .addComponent(bLimpiarCamposRegCurso))
                .addGap(36, 36, 36))
        );

        rQRegistrarEsqArea.setMinimumSize(new java.awt.Dimension(1000, 1000));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Registrar Escuela o Área Académica");

        jLabel4.setText("Nombre: ");

        jLabel5.setText("Código");

        tCodigoEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCodigoEscuelaActionPerformed(evt);
            }
        });

        bRegEsqArea.setText("Registrar");
        bRegEsqArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegEsqAreaActionPerformed(evt);
            }
        });

        jButton6.setText("Limpiar Casillas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tNombreEA, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(tCodigoEscuela)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(bRegEsqArea)
                        .addGap(63, 63, 63)
                        .addComponent(jButton6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tNombreEA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tCodigoEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegEsqArea)
                    .addComponent(jButton6))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout rQRegistrarEsqAreaLayout = new javax.swing.GroupLayout(rQRegistrarEsqArea.getContentPane());
        rQRegistrarEsqArea.getContentPane().setLayout(rQRegistrarEsqAreaLayout);
        rQRegistrarEsqAreaLayout.setHorizontalGroup(
            rQRegistrarEsqAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rQRegistrarEsqAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rQRegistrarEsqAreaLayout.setVerticalGroup(
            rQRegistrarEsqAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rQRegistrarEsqAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbAsignarReqCorreq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAsignarReqCorreq.setText("Asignar requisitos y correquisitos a un curso");

        lbEscuelaPropietariaCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEscuelaPropietariaCurso.setText("Escuela propietaria del curso");

        cbEscuelasPropietariasCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEscuelasPropietariasCursoActionPerformed(evt);
            }
        });

        lbCodCurso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCodCurso.setText("Código del curso:");

        cbCodigosCursosDeEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCodigosCursosDeEscuelaActionPerformed(evt);
            }
        });

        lbReqs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbReqs.setText("Requisitos del curso");

        lbCorreqs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCorreqs.setText("Correquisitos del curso");

        lbCodCursoReq.setText("Código del curso:");

        lbCodCursoCorreq.setText("Código del curso:");

        bRegistrarRequisito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bRegistrarRequisito.setText("Registrar requisito");
        bRegistrarRequisito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarRequisitoActionPerformed(evt);
            }
        });

        bRegistrarCorrequisito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bRegistrarCorrequisito.setText("Registrar correquisito");
        bRegistrarCorrequisito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarCorrequisitoActionPerformed(evt);
            }
        });

        bCerrarRegReqCorreq.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bCerrarRegReqCorreq.setText("Cerrar");
        bCerrarRegReqCorreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarRegReqCorreqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rqRegistrarRequeCorrequeLayout = new javax.swing.GroupLayout(rqRegistrarRequeCorreque.getContentPane());
        rqRegistrarRequeCorreque.getContentPane().setLayout(rqRegistrarRequeCorrequeLayout);
        rqRegistrarRequeCorrequeLayout.setHorizontalGroup(
            rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rqRegistrarRequeCorrequeLayout.createSequentialGroup()
                .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rqRegistrarRequeCorrequeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEscuelaPropietariaCurso)
                            .addComponent(lbCodCurso))
                        .addGap(18, 18, 18)
                        .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEscuelasPropietariasCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(rqRegistrarRequeCorrequeLayout.createSequentialGroup()
                                .addComponent(cbCodigosCursosDeEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(rqRegistrarRequeCorrequeLayout.createSequentialGroup()
                        .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rqRegistrarRequeCorrequeLayout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(bCerrarRegReqCorreq, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rqRegistrarRequeCorrequeLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(lbAsignarReqCorreq)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(rqRegistrarRequeCorrequeLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rqRegistrarRequeCorrequeLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCodCursoReq)
                            .addComponent(cbCodigoCursoReq, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbReqs))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rqRegistrarRequeCorrequeLayout.createSequentialGroup()
                        .addComponent(bRegistrarRequisito, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbCodCursoCorreq)
                        .addComponent(lbCorreqs)
                        .addComponent(cbCodigoCursoCorreq, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bRegistrarCorrequisito))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        rqRegistrarRequeCorrequeLayout.setVerticalGroup(
            rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rqRegistrarRequeCorrequeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbAsignarReqCorreq)
                .addGap(27, 27, 27)
                .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEscuelasPropietariasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEscuelaPropietariaCurso))
                .addGap(18, 18, 18)
                .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodCurso)
                    .addComponent(cbCodigosCursosDeEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbReqs)
                    .addComponent(lbCorreqs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodCursoReq)
                    .addComponent(lbCodCursoCorreq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCodigoCursoReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCodigoCursoCorreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rqRegistrarRequeCorrequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegistrarRequisito)
                    .addComponent(bRegistrarCorrequisito))
                .addGap(36, 36, 36)
                .addComponent(bCerrarRegReqCorreq)
                .addContainerGap())
        );

        rqAsignarPlanDeEstudio.setMinimumSize(new java.awt.Dimension(650, 650));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Registro de Planes de Estudio ");

        jLabel6.setText("Escuela asociada del plan:");

        jLabel8.setText("Código del plan de estudios:");

        jLabel9.setText("Vigencia del plan de estudios:");

        cboxPlanesEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPlanesEstActionPerformed(evt);
            }
        });

        jLabel11.setText("Código del curso que forma parte del plan: ");

        jLabel12.setText("Bloque");

        bPropioRegistroVentana.setText("Registrar cursos en el plan de estudios");
        bPropioRegistroVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPropioRegistroVentanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bPropioRegistroVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(bPropioRegistroVentana)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rqAsignarPlanDeEstudioLayout = new javax.swing.GroupLayout(rqAsignarPlanDeEstudio.getContentPane());
        rqAsignarPlanDeEstudio.getContentPane().setLayout(rqAsignarPlanDeEstudioLayout);
        rqAsignarPlanDeEstudioLayout.setHorizontalGroup(
            rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                        .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(32, 32, 32)
                        .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboxBloqueActivo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigoCurso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                        .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98)
                        .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxPlanesEst, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CalendVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        rqAsignarPlanDeEstudioLayout.setVerticalGroup(
            rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboxPlanesEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9))
                    .addGroup(rqAsignarPlanDeEstudioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CalendVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(rqAsignarPlanDeEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cboxBloqueActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rqConsultaPlanEstudio.setMinimumSize(new java.awt.Dimension(740, 500));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Consultar plan de estudios");

        jLabel13.setText("Escuela propietaria del plan:");

        jEscuelaprop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Codigo del plan de estudios:");

        jMostrarCodPlan.setText("jTextField1");

        jLabel15.setText("Vigencia del plan de estudios:");

        bPDFCorreo.setText("Generar PDF y enviar por correo");

        tabPlanEstudio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabPlanEstudio);

        jButton5.setText("Regresar");

        javax.swing.GroupLayout rqConsultaPlanEstudioLayout = new javax.swing.GroupLayout(rqConsultaPlanEstudio.getContentPane());
        rqConsultaPlanEstudio.getContentPane().setLayout(rqConsultaPlanEstudioLayout);
        rqConsultaPlanEstudioLayout.setHorizontalGroup(
            rqConsultaPlanEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rqConsultaPlanEstudioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(rqConsultaPlanEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rqConsultaPlanEstudioLayout.createSequentialGroup()
                        .addGroup(rqConsultaPlanEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(94, 94, 94)
                        .addGroup(rqConsultaPlanEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rqConsultaPlanEstudioLayout.createSequentialGroup()
                                .addComponent(jEscuelaprop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jLabel14)
                                .addGap(35, 35, 35)
                                .addComponent(jMostrarCodPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMostrarVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bPDFCorreo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rqConsultaPlanEstudioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(46, 46, 46))
        );
        rqConsultaPlanEstudioLayout.setVerticalGroup(
            rqConsultaPlanEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rqConsultaPlanEstudioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rqConsultaPlanEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rqConsultaPlanEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jEscuelaprop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jMostrarCodPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rqConsultaPlanEstudioLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGap(42, 42, 42)
                .addGroup(rqConsultaPlanEstudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jMostrarVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(bPDFCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bVentanaRegistrarEscuela.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bVentanaRegistrarEscuela.setText("Registrar escuela o Área Académica");
        bVentanaRegistrarEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVentanaRegistrarEscuelaActionPerformed(evt);
            }
        });

        bVentanaRegistrarCursos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bVentanaRegistrarCursos.setText("Registrar Cursos");
        bVentanaRegistrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVentanaRegistrarCursosActionPerformed(evt);
            }
        });

        jBInterfRegPlanesEstudio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBInterfRegPlanesEstudio.setText("Crear un Plan de Estudios");
        jBInterfRegPlanesEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInterfRegPlanesEstudioActionPerformed(evt);
            }
        });

        jBVisualizarPlanes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBVisualizarPlanes.setText("Consultar Plan de Estudios");
        jBVisualizarPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVisualizarPlanesActionPerformed(evt);
            }
        });

        bVentanaRegistrarReqCorreq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bVentanaRegistrarReqCorreq.setText("Registrar requisitos y correquisitos a un curso");
        bVentanaRegistrarReqCorreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVentanaRegistrarReqCorreqActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Sistema Gestor de Planes de Estudio");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("¡Bienvenido al Gestor de Planes de Estudio *inserte nombre bonito*!");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Por favor, seleccione la acción que desea realizar:");

        bVentanaConsultarPlanesConCiertoCurso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bVentanaConsultarPlanesConCiertoCurso.setText("Consultar planes de estudio con curso en particular");

        bVentanaConsultarRequisitos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bVentanaConsultarRequisitos.setText("Consultar los requisitos de un curso");

        bVentanaConsultarCorrequisitos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bVentanaConsultarCorrequisitos.setText("Consultar los correquisitos de un curso");

        bVentanaEliminarReqCurso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bVentanaEliminarReqCurso.setText("Eliminar el requisito de un curso");

        bVentanaEliminarCursoPlanDeEstudio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bVentanaEliminarCursoPlanDeEstudio.setText("Eliminar un curso de un plan de estudios");

        bVentanaEliminarCurso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bVentanaEliminarCurso.setText("Eliminar un curso");
        bVentanaEliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVentanaEliminarCursoActionPerformed(evt);
            }
        });

        jLabel17.setText("notita: estos de la derecha se ven medio feos fdsjfj creo que se ve muy cargado? o como lo ves vos D:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bVentanaRegistrarReqCorreq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBInterfRegPlanesEstudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBVisualizarPlanes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bVentanaRegistrarCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bVentanaRegistrarEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bVentanaConsultarPlanesConCiertoCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bVentanaConsultarRequisitos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bVentanaConsultarCorrequisitos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bVentanaEliminarReqCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bVentanaEliminarCursoPlanDeEstudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bVentanaEliminarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(156, 156, 156)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel17)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bVentanaConsultarPlanesConCiertoCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVentanaConsultarRequisitos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVentanaConsultarCorrequisitos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVentanaEliminarReqCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVentanaEliminarCursoPlanDeEstudio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVentanaEliminarCurso)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bVentanaRegistrarEscuela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVentanaRegistrarCursos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVentanaRegistrarReqCorreq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBInterfRegPlanesEstudio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBVisualizarPlanes)
                        .addGap(41, 41, 41))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCodigoEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCodigoEscuelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCodigoEscuelaActionPerformed

    private void bRegEsqAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegEsqAreaActionPerformed
        Controlador entradaCon = new Controlador();
        if(this.tNombreEA.getText().equals("")){
            JOptionPane.showMessageDialog(null,"¡Espacio en blanco! Por favor, ingrese un nombre de escuela válido");
        }
        
            
        if(this.tCodigoEscuela.getText().equals("")){
            JOptionPane.showMessageDialog(null,"¡Espacio en blanco! Por favor, ingrese un codigo de escuela válido");
        }
        try {
            entradaCon.crearEscuela(tNombreEA.getText(), tCodigoEscuela.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bRegEsqAreaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    this.tCodigoEscuela.setText(null);
    this.tNombreEA.setText(null);
    }//GEN-LAST:event_jButton6ActionPerformed


    private void nombresEscuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresEscuelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresEscuelasActionPerformed

    private void nombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCursoActionPerformed

    private void numCodCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCodCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCodCursoActionPerformed

    private void numCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCreditosActionPerformed

    private void cantHorasLectivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantHorasLectivasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantHorasLectivasActionPerformed

    private void bRegistrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarCursoActionPerformed
        Controlador entradaCon = new Controlador();
        //String nombreEscuela = cbNombresEscuelas.getSelectedItem().toString();
        if(this.tNombreCurso.getText().equals("")){
            JOptionPane.showMessageDialog(null,"¡Espacio en blanco! Por favor, ingrese un nombre de curso válido");
        }
        //validar que no repita el nombre
        
        String numCodCurso = this.tNumCodCurso.getText();
        if(this.tNumCodCurso.getText().equals("")){
            JOptionPane.showMessageDialog(null,"¡Espacio en blanco! Por favor, ingrese un número de curso válido");
        }
        
        try{
            int intCodCurso = Integer.parseInt(numCodCurso);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"¡Entrada inválida! Por favor, ingrese un número entero para el curso");
        }
        
        int cantCreditos = Integer.valueOf(cbNumCreditos.getSelectedItem().toString());        
        int cantHorasLectivas = Integer.valueOf(cbCantHorasLectivas.getSelectedItem().toString());
        
        String codCurso = seleccionarCodigoEscuela() + this.tNumCodCurso.getText();

        //validar num de 4 dig
        //validar que no repita el num 
        
        entradaCon.crearCurso(seleccionarCodigoEscuela(), this.tNombreCurso.getText(), codCurso, cantCreditos, cantHorasLectivas);
         
        
    }//GEN-LAST:event_bRegistrarCursoActionPerformed

    private void bLimpiarCamposRegCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarCamposRegCursoActionPerformed
        this.tNombreCurso.setText(null);
        this.tNumCodCurso.setText(null);
        this.lbCodEscuelaCodCurso.setText(null);
    }//GEN-LAST:event_bLimpiarCamposRegCursoActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    private void botonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cbNombresEscuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNombresEscuelasActionPerformed
        String nombreEscuela = cbNombresEscuelas.getSelectedItem().toString();
        String codEscuela = contrl.obtenerCodEscuela(nombreEscuela); 
        System.out.println(codEscuela);
        this.lbCodEscuelaCodCurso.setText(codEscuela);
    }//GEN-LAST:event_cbNombresEscuelasActionPerformed

    private void tNumCodCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNumCodCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNumCodCursoActionPerformed

    private void tNombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreCursoActionPerformed

    private void jBInterfRegPlanesEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInterfRegPlanesEstudioActionPerformed
        contrl.poblarCboxEscuelas2(cboxPlanesEst);
        poblarCboxBloqueActivo(cboxBloqueActivo);
        this.rqAsignarPlanDeEstudio.setVisible(true);
    }//GEN-LAST:event_jBInterfRegPlanesEstudioActionPerformed

    private void bVentanaRegistrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVentanaRegistrarCursosActionPerformed
        contrl.poblarCboxEscuelas(cbNombresEscuelas);
        poblarCboxCreditos(cbNumCreditos);
        poblarCboxHorasLectivas(cbCantHorasLectivas);
        this.rQRegCursos.setVisible(true);  
    }//GEN-LAST:event_bVentanaRegistrarCursosActionPerformed

    private void bVentanaRegistrarEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVentanaRegistrarEscuelaActionPerformed
        this.rQRegistrarEsqArea.setVisible(true);
    }//GEN-LAST:event_bVentanaRegistrarEscuelaActionPerformed

    private void cboxPlanesEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPlanesEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxPlanesEstActionPerformed

    private void bPropioRegistroVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPropioRegistroVentanaActionPerformed
   
        try{
            cboxPlanesEst.getSelectedItem().toString();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Por favor, seleccione un espacio valido");
        }
        
        if(this.txtCodigoPlan.getText().equals("")){
            JOptionPane.showMessageDialog(null,"¡Espacio en blanco! Por favor, ingrese un nombre de curso válido");
        }
        if(this.txtCodigoCurso.getText().equals("")){
            JOptionPane.showMessageDialog(null,"¡Espacio en blanco! Por favor, ingrese un nombre de curso válido");
        }
        
        try{
            this.cboxBloqueActivo.getSelectedItem().toString();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Por favor, seleccione un espacio valido");
        }
        
        
        // variable 
        String nombreEscuela= cboxPlanesEst.getSelectedItem().toString();
        String codigoCurso=txtCodigoCurso.getText();
        int codigoPlan = Integer.parseInt(txtCodigoPlan.getText());
        String bloqueActivo =this.cboxBloqueActivo.getSelectedItem().toString();
        
        //Conversion jCalendar
        Date vigenciaPlan  = CalendVigencia.getDate();
        long fechaconv= vigenciaPlan.getTime();
        java.sql.Date fechaSql= new java.sql.Date(fechaconv);
        
        //Llamada al controlador
        contrl.crearPlanEstudios(nombreEscuela,codigoPlan,fechaSql,codigoCurso,bloqueActivo);        
    }//GEN-LAST:event_bPropioRegistroVentanaActionPerformed

    private void jBVisualizarPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVisualizarPlanesActionPerformed
       this.rqConsultaPlanEstudio.setVisible(true);
    }//GEN-LAST:event_jBVisualizarPlanesActionPerformed

    private void bRegistrarRequisitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarRequisitoActionPerformed
        //String nombreEscuela = cbEscuelasPropietariasCurso.getSelectedItem().toString();
        //String codEscuela = contrl.obtenerCodEscuela(nombreEscuela);
        try{
            String codCurso = cbCodigosCursosDeEscuela.getSelectedItem().toString();
            String codCursoRequisito = cbCodigoCursoReq.getSelectedItem().toString();
            System.out.println(codCursoRequisito);
            //Llamar al controlador para hacer la insercion del requisito
            contrl.agregarRequisitoACurso(codCurso, codCursoRequisito); 
        }
        catch(NullPointerException e){
            //agregar mensajito de error
            System.out.println("Codreq vacio");
        }
         
    }//GEN-LAST:event_bRegistrarRequisitoActionPerformed

    private void bVentanaEliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVentanaEliminarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVentanaEliminarCursoActionPerformed

    private void bVentanaRegistrarReqCorreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVentanaRegistrarReqCorreqActionPerformed
        contrl.poblarCboxEscuelas(cbEscuelasPropietariasCurso);
        this.rqRegistrarRequeCorreque.setVisible(true);
    }//GEN-LAST:event_bVentanaRegistrarReqCorreqActionPerformed

    private void cbEscuelasPropietariasCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEscuelasPropietariasCursoActionPerformed
        String nombreEscuela = cbEscuelasPropietariasCurso.getSelectedItem().toString();
        String codEscuela = contrl.obtenerCodEscuela(nombreEscuela); 
        this.cbCodigosCursosDeEscuela.removeAllItems();
        contrl.poblarCboxCursosDeEscuela(cbCodigosCursosDeEscuela, codEscuela);
    }//GEN-LAST:event_cbEscuelasPropietariasCursoActionPerformed

    private void cbCodigosCursosDeEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCodigosCursosDeEscuelaActionPerformed
        contrl.poblarCboxCursos(cbCodigoCursoReq);
        contrl.poblarCboxCursos(cbCodigoCursoCorreq);
        cbCodigoCursoReq.setSelectedIndex(-1);
        cbCodigoCursoCorreq.setSelectedIndex(-1);
    }//GEN-LAST:event_cbCodigosCursosDeEscuelaActionPerformed

    private void bRegistrarCorrequisitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarCorrequisitoActionPerformed
        //String nombreEscuela = cbEscuelasPropietariasCurso.getSelectedItem().toString();
        //String codEscuela = contrl.obtenerCodEscuela(nombreEscuela);
        try{
            String codCurso = cbCodigosCursosDeEscuela.getSelectedItem().toString();
            String codCursoCorrequisito = cbCodigoCursoCorreq.getSelectedItem().toString();
            System.out.println(codCursoCorrequisito);
        
            //Llamar al controlador para hacer la insercion del requisito
            contrl.agregarCorrequisitoACurso(codCurso, codCursoCorrequisito);
        }
        catch(NullPointerException e){
            //agregar mensajito de error
            System.out.println("CodCorreq vacio");
        }
    }//GEN-LAST:event_bRegistrarCorrequisitoActionPerformed

    private void bCerrarRegReqCorreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarRegReqCorreqActionPerformed
        this.rqRegistrarRequeCorreque.dispose();
    }//GEN-LAST:event_bCerrarRegReqCorreqActionPerformed

    private String seleccionarCodigoEscuela(){
        String nombreEscuela = cbNombresEscuelas.getSelectedItem().toString();
        String codEscuela = contrl.obtenerCodEscuela(nombreEscuela); 
        return codEscuela;
    }
    
    private void poblarCboxCreditos(JComboBox cbox_Creditos){
        int contador = 0;
        while (10 > contador){
            cbox_Creditos.addItem(contador);
            contador++;
        }   
    } 
    
    private void poblarCboxHorasLectivas(JComboBox cbox_horasLectivas){
        int contador = 0;
        while (24 > contador){
            cbox_horasLectivas.addItem(contador);
            contador++;
        }  
    }
    
    private void poblarCboxBloqueActivo(JComboBox cboxBloqueActivo){
        int contador = 0;
        String[] listaBloques = {"I Semestre","II Semestre", "Verano"};
        for(int i=0; i<listaBloques.length ;++i){
            cboxBloqueActivo.addItem(listaBloques[i]);
            contador++;
        }  
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar CalendVigencia;
    private javax.swing.JButton bCerrarRegReqCorreq;
    private javax.swing.JButton bLimpiarCamposRegCurso;
    private javax.swing.JButton bPDFCorreo;
    private javax.swing.JButton bPropioRegistroVentana;
    private javax.swing.JButton bRegEsqArea;
    private javax.swing.JButton bRegistrarCorrequisito;
    private javax.swing.JButton bRegistrarCurso;
    private javax.swing.JButton bRegistrarRequisito;
    private javax.swing.JButton bVentanaConsultarCorrequisitos;
    private javax.swing.JButton bVentanaConsultarPlanesConCiertoCurso;
    private javax.swing.JButton bVentanaConsultarRequisitos;
    private javax.swing.JButton bVentanaEliminarCurso;
    private javax.swing.JButton bVentanaEliminarCursoPlanDeEstudio;
    private javax.swing.JButton bVentanaEliminarReqCurso;
    private javax.swing.JButton bVentanaRegistrarCursos;
    private javax.swing.JButton bVentanaRegistrarEscuela;
    private javax.swing.JButton bVentanaRegistrarReqCorreq;
    private javax.swing.JComboBox<String> cbCantHorasLectivas;
    private javax.swing.JComboBox<String> cbCodigoCursoCorreq;
    private javax.swing.JComboBox<String> cbCodigoCursoReq;
    private javax.swing.JComboBox<String> cbCodigosCursosDeEscuela;
    private javax.swing.JComboBox<String> cbEscuelasPropietariasCurso;
    private javax.swing.JComboBox<String> cbNombresEscuelas;
    private javax.swing.JComboBox<String> cbNumCreditos;
    private javax.swing.JComboBox<String> cboxBloqueActivo;
    private javax.swing.JComboBox<String> cboxPlanesEst;
    private javax.swing.JButton jBInterfRegPlanesEstudio;
    private javax.swing.JButton jBVisualizarPlanes;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jEscuelaprop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMostrarCodPlan;
    private javax.swing.JTextField jMostrarVigencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCodCurso;
    private javax.swing.JLabel labelCreditosCurso;
    private javax.swing.JLabel labelEscuela;
    private javax.swing.JLabel labelHorasLectivas;
    private javax.swing.JLabel labelNombreCurso;
    private javax.swing.JLabel labelRegistroCursos;
    private javax.swing.JLabel lbAsignarReqCorreq;
    private javax.swing.JLabel lbCodCurso;
    private javax.swing.JLabel lbCodCursoCorreq;
    private javax.swing.JLabel lbCodCursoReq;
    private javax.swing.JLabel lbCodEscuelaCodCurso;
    private javax.swing.JLabel lbCorreqs;
    private javax.swing.JLabel lbEscuelaPropietariaCurso;
    private javax.swing.JLabel lbReqs;
    private javax.swing.JFrame rQRegCursos;
    private javax.swing.JFrame rQRegistrarEsqArea;
    private javax.swing.JFrame rqAsignarPlanDeEstudio;
    private javax.swing.JFrame rqConsultaPlanEstudio;
    private javax.swing.JFrame rqRegistrarRequeCorreque;
    private javax.swing.JTextField tCodigoEscuela;
    private javax.swing.JTextField tNombreCurso;
    private javax.swing.JTextField tNombreEA;
    private javax.swing.JTextField tNumCodCurso;
    private javax.swing.JTable tabPlanEstudio;
    private javax.swing.JTextField txtCodigoCurso;
    private javax.swing.JTextField txtCodigoPlan;
    // End of variables declaration//GEN-END:variables
}
